# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportPeriodePlusLabel.ui'
#
# Created: Thu Aug 02 02:53:16 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 528)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEditJumQty = QtGui.QLineEdit(self.centralwidget)
        self.lineEditJumQty.setEnabled(False)
        self.lineEditJumQty.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditJumQty.setFont(font)
        self.lineEditJumQty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditJumQty.setObjectName(_fromUtf8("lineEditJumQty"))
        self.gridLayout_4.addWidget(self.lineEditJumQty, 1, 1, 1, 1)
        self.lineEditJumHargaSebelum = QtGui.QLineEdit(self.centralwidget)
        self.lineEditJumHargaSebelum.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditJumHargaSebelum.setFont(font)
        self.lineEditJumHargaSebelum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditJumHargaSebelum.setObjectName(_fromUtf8("lineEditJumHargaSebelum"))
        self.gridLayout_4.addWidget(self.lineEditJumHargaSebelum, 0, 3, 1, 1)
        self.lineEditJumHargaSetelah = QtGui.QLineEdit(self.centralwidget)
        self.lineEditJumHargaSetelah.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditJumHargaSetelah.setFont(font)
        self.lineEditJumHargaSetelah.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditJumHargaSetelah.setObjectName(_fromUtf8("lineEditJumHargaSetelah"))
        self.gridLayout_4.addWidget(self.lineEditJumHargaSetelah, 1, 3, 1, 1)
        self.lineEditJumCust = QtGui.QLineEdit(self.centralwidget)
        self.lineEditJumCust.setEnabled(False)
        self.lineEditJumCust.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditJumCust.setFont(font)
        self.lineEditJumCust.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditJumCust.setObjectName(_fromUtf8("lineEditJumCust"))
        self.gridLayout_4.addWidget(self.lineEditJumCust, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 6, 1, 1)
        self.labelLaba = QtGui.QLabel(self.centralwidget)
        self.labelLaba.setObjectName(_fromUtf8("labelLaba"))
        self.gridLayout_4.addWidget(self.labelLaba, 0, 4, 1, 1)
        self.lineEditLaba = QtGui.QLineEdit(self.centralwidget)
        self.lineEditLaba.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLaba.setFont(font)
        self.lineEditLaba.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditLaba.setObjectName(_fromUtf8("lineEditLaba"))
        self.gridLayout_4.addWidget(self.lineEditLaba, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 4, 0, 1, 4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonReset = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);\n"
"color: rgb(255, 255, 255);"))
        self.pushButtonReset.setFlat(False)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout_3.addWidget(self.pushButtonReset, 0, 2, 1, 1)
        self.lineEditCari = QtGui.QLineEdit(self.centralwidget)
        self.lineEditCari.setObjectName(_fromUtf8("lineEditCari"))
        self.gridLayout_3.addWidget(self.lineEditCari, 0, 1, 1, 1)
        self.comboBoxSearch = QtGui.QComboBox(self.centralwidget)
        self.comboBoxSearch.setObjectName(_fromUtf8("comboBoxSearch"))
        self.gridLayout_3.addWidget(self.comboBoxSearch, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateEditAkhir = QtGui.QDateEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditAkhir.sizePolicy().hasHeightForWidth())
        self.dateEditAkhir.setSizePolicy(sizePolicy)
        self.dateEditAkhir.setCalendarPopup(True)
        self.dateEditAkhir.setObjectName(_fromUtf8("dateEditAkhir"))
        self.gridLayout.addWidget(self.dateEditAkhir, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/zoom.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 4)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelTipe = QtGui.QLabel(self.centralwidget)
        self.labelTipe.setObjectName(_fromUtf8("labelTipe"))
        self.gridLayout.addWidget(self.labelTipe, 0, 2, 1, 1)
        self.dateEditAwal = QtGui.QDateEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditAwal.sizePolicy().hasHeightForWidth())
        self.dateEditAwal.setSizePolicy(sizePolicy)
        self.dateEditAwal.setCalendarPopup(True)
        self.dateEditAwal.setObjectName(_fromUtf8("dateEditAwal"))
        self.gridLayout.addWidget(self.dateEditAwal, 0, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionExport_Excel = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/file_extension_xls.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Excel.setIcon(icon)
        self.actionExport_Excel.setObjectName(_fromUtf8("actionExport_Excel"))
        self.actionShow_Data = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/application_form_magnify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Data.setIcon(icon1)
        self.actionShow_Data.setObjectName(_fromUtf8("actionShow_Data"))
        self.actionKeluar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/door_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKeluar.setIcon(icon2)
        self.actionKeluar.setObjectName(_fromUtf8("actionKeluar"))
        self.actionGrafik = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/chart_bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrafik.setIcon(icon3)
        self.actionGrafik.setObjectName(_fromUtf8("actionGrafik"))
        self.toolBar.addAction(self.actionShow_Data)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "Jumlah Harga Setelah Disc", None))
        self.label_5.setText(_translate("MainWindow", "Jumlah Qty Item", None))
        self.label_3.setText(_translate("MainWindow", "Jumlah Customer Transaksi", None))
        self.label_6.setText(_translate("MainWindow", "Jumlah Harga Sebelum Disc", None))
        self.labelLaba.setText(_translate("MainWindow", "TOTAL LABA ", None))
        self.pushButtonReset.setText(_translate("MainWindow", "RESET", None))
        self.label_2.setText(_translate("MainWindow", "Tanggal Akhir :", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Semua", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Tunai", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Kredit", None))
        self.tableWidget.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Tanggal Awal :", None))
        self.labelTipe.setText(_translate("MainWindow", "Tipe Bayar :", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExport_Excel.setText(_translate("MainWindow", "Export Excel", None))
        self.actionShow_Data.setText(_translate("MainWindow", "Show Data", None))
        self.actionKeluar.setText(_translate("MainWindow", "Keluar", None))
        self.actionGrafik.setText(_translate("MainWindow", "Grafik", None))

import icon_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

